# We cannot reuse the build from the main Builder workflow
# due to needing to inject SENTRY_ env vars into ci_package.sh
# For security we harbor the secrets in a develop-only environment.
name: Sentry Sourcemaps
on:
  push:
    branches:
      - develop
  repository_dispatch:
    types: [ element-web-notify ]
jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Dependencies
        run: "./scripts/layered.sh"

      - name: Build & Package
        run: "./scripts/ci_package.sh"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_ORG: sentry
          SENTRY_PROJECT: riot-web
