name: Test
on:
  pull_request: { }
  push:
    branches: [ master, develop ]
  repository_dispatch:
    types: [ element-web-notify ]
jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    env:
      # This must be set for fetchdep.sh to get the right branch
      PR_NUMBER: ${{github.event.number}}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install Dependencies
        run: "./scripts/layered.sh"

      - name: Run Tests
        run: "yarn test"
